// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models {
    #pragma warning disable CS1591
    public class Carrera : IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>The codigo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Codigo? Codigo { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Codigo Codigo { get; set; }
#endif
        /// <summary>The contenidos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        //public List<Contenido>? Contenidos { get; private set; }
#nullable restore
#else
        public List<Contenido> Contenidos { get; private set; }
#endif
        /// <summary>The escuela property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre? Escuela { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre Escuela { get; set; }
#endif
        /// <summary>The isSteam property</summary>
        public bool? IsSteam { get; set; }
        /// <summary>The nombre property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre? Nombre { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre Nombre { get; set; }
#endif
        /// <summary>The presupuestoBecas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Budget? PresupuestoBecas { get; set; }
#nullable restore
#else
        public Budget PresupuestoBecas { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Carrera"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Carrera CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Carrera();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"codigo", n => { Codigo = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Codigo>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Codigo.CreateFromDiscriminatorValue); } },
                //{"contenidos", n => { Contenidos = n.GetCollectionOfObjectValues<Contenido>(Contenido.CreateFromDiscriminatorValue)?.ToList(); } },
                {"escuela", n => { Escuela = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre.CreateFromDiscriminatorValue); } },
                {"isSteam", n => { IsSteam = n.GetBoolValue(); } },
                {"nombre", n => { Nombre = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre.CreateFromDiscriminatorValue); } },
                {"presupuestoBecas", n => { PresupuestoBecas = n.GetObjectValue<Budget>(Budget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Codigo>("codigo", Codigo);
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>("escuela", Escuela);
            writer.WriteBoolValue("isSteam", IsSteam);
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>("nombre", Nombre);
            writer.WriteObjectValue<Budget>("presupuestoBecas", PresupuestoBecas);
        }
    }
}
