// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models {
    #pragma warning disable CS1591
    public class Contenido : IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>The acronimo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Acronimo? Acronimo { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Acronimo Acronimo { get; set; }
#endif
        /// <summary>The carreras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        //public List<Carrera>? Carreras { get; private set; }
#nullable restore
#else
        // public List<Carrera> Carreras { get; private set; }
#endif
        /// <summary>The creditos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Creditos? Creditos { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Creditos Creditos { get; set; }
#endif
        /// <summary>The nombre property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre? Nombre { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre Nombre { get; set; }
#endif
        /// <summary>The tipo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public TipoContenido? Tipo { get; set; }
#nullable restore
#else
        public TipoContenido Tipo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Contenido"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Contenido CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Contenido();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"acronimo", n => { Acronimo = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Acronimo>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Acronimo.CreateFromDiscriminatorValue); } },
                //{"carreras", n => { Carreras = n.GetCollectionOfObjectValues<Carrera>(Carrera.CreateFromDiscriminatorValue)?.ToList(); } },
                {"creditos", n => { Creditos = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Creditos>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Creditos.CreateFromDiscriminatorValue); } },
                {"nombre", n => { Nombre = n.GetObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>(UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre.CreateFromDiscriminatorValue); } },
                {"tipo", n => { Tipo = n.GetObjectValue<TipoContenido>(TipoContenido.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Acronimo>("acronimo", Acronimo);
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Creditos>("creditos", Creditos);
            writer.WriteObjectValue<UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.Models.Nombre>("nombre", Nombre);
            writer.WriteObjectValue<TipoContenido>("tipo", Tipo);
        }
    }
}
