// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.AddContenidoCarrera;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.CreateCarrera;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.CreateContenidos;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.ListCarreras;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.ListContenidos;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.ListContenidosCarrera;
using UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client.UpdateCarreraScholarshipBudget;
namespace UCR.ECCI.IS.EvaluacionTecnica.Infrastructure.ApiClient.Client {
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    public class ApiClientKiota : BaseRequestBuilder 
    {
        /// <summary>The addContenidoCarrera property</summary>
        public AddContenidoCarreraRequestBuilder AddContenidoCarrera
        {
            get => new AddContenidoCarreraRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createCarrera property</summary>
        public CreateCarreraRequestBuilder CreateCarrera
        {
            get => new CreateCarreraRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createContenidos property</summary>
        public CreateContenidosRequestBuilder CreateContenidos
        {
            get => new CreateContenidosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listCarreras property</summary>
        public ListCarrerasRequestBuilder ListCarreras
        {
            get => new ListCarrerasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listContenidos property</summary>
        public ListContenidosRequestBuilder ListContenidos
        {
            get => new ListContenidosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listContenidosCarrera property</summary>
        public ListContenidosCarreraRequestBuilder ListContenidosCarrera
        {
            get => new ListContenidosCarreraRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateCarreraScholarshipBudget property</summary>
        public UpdateCarreraScholarshipBudgetRequestBuilder UpdateCarreraScholarshipBudget
        {
            get => new UpdateCarreraScholarshipBudgetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiClientKiota"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClientKiota(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
